### ISSUE TITLE
KeyError: 'dataset_type' with other Json files

### ISSUE THREAD

**Issue by HareRee** [ckan/ckanext-scheming#209]
{"ckan_version": "2.7.3", "extensions": ["stats", "text_view", "image_view", "recline_view", "harvest", "ckan_harvester", "oaipmh_harvester", "scheming_datasets"]}

When I use the `camel_photos.json` file the `camel-photos/new` url loads fine.  

However, when I try using any other json / schema that's included it get an error (see stack below).
`scheming.dataset_schemas = ckanext.scheming:custom_org_with_address.json`
```
[Mon May 13 05:13:47.988295 2019] [:error] [pid 4989] [remote 192.168.70.1:0] mod_wsgi (pid=4989): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Mon May 13 05:13:47.988344 2019] [:error] [pid 4989] [remote 192.168.70.1:0] mod_wsgi (pid=4989): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Mon May 13 05:13:47.988362 2019] [:error] [pid 4989] [remote 192.168.70.1:0] Traceback (most recent call last):
[Mon May 13 05:13:47.988377 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/etc/ckan/default/apache.wsgi", line 12, in <module>
[Mon May 13 05:13:47.988396 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     application = loadapp('config:%s' % config_filepath)
[Mon May 13 05:13:47.988402 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon May 13 05:13:47.988414 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     return loadobj(APP, uri, name=name, **kw)
[Mon May 13 05:13:47.988420 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Mon May 13 05:13:47.988428 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     return context.create()
[Mon May 13 05:13:47.988433 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Mon May 13 05:13:47.988441 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     return self.object_type.invoke(self)
[Mon May 13 05:13:47.988446 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Mon May 13 05:13:47.988454 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Mon May 13 05:13:47.988458 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Mon May 13 05:13:47.988467 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     val = callable(*args, **kw)
[Mon May 13 05:13:47.988472 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 46, in make_app
[Mon May 13 05:13:47.988481 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     load_environment(conf, app_conf)
[Mon May 13 05:13:47.988490 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
[Mon May 13 05:13:47.988500 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     p.load_all()
[Mon May 13 05:13:47.988505 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
[Mon May 13 05:13:47.988513 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     load(*plugins)
[Mon May 13 05:13:47.988517 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
[Mon May 13 05:13:47.988525 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     plugins_update()
[Mon May 13 05:13:47.988538 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
[Mon May 13 05:13:47.988547 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     environment.update_config()
[Mon May 13 05:13:47.988552 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 150, in update_config
[Mon May 13 05:13:47.988560 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     plugin.update_config(config)
[Mon May 13 05:13:47.988564 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 158, in update_config
[Mon May 13 05:13:47.988573 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     self.SCHEMA_TYPE_FIELD
[Mon May 13 05:13:47.988578 2019] [:error] [pid 4989] [remote 192.168.70.1:0]   File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 352, in _load_schemas
[Mon May 13 05:13:47.988585 2019] [:error] [pid 4989] [remote 192.168.70.1:0]     out[schema[type_field]] = schema
[Mon May 13 05:13:47.988599 2019] [:error] [pid 4989] [remote 192.168.70.1:0] KeyError: 'dataset_type'
```

**Comment by HareRee** [comment]
Oh this is a Org schema..
